version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://musicdb_usga_user:0PZ0dKd8uJCHhIwOvmA5yasi6d3bqWeM@dpg-csfl8908fa8c739vnkhg-a/musicdb_usga
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=musicdb_usga_user
      - POSTGRES_PASSWORD=0PZ0dKd8uJCHhIwOvmA5yasi6d3bqWeM
      - POSTGRES_DB=musicdb_usga
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge 